[tool]
[tool.poetry]
name = 'Lilliebot'
version = '0.13'
description = "the bot gen 1"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
discord = "^1.0"
flask = "^1.1"
"discord.py" = "^1.3"

 